#!/bin/bash

source /home/jungwook/tt-metal_moreh/python_env/bin/activate

#export PROFILE_TRACE=1
#export PROFILE_ENABLE_TRACE_LOG=1

export VLLM_TARGET_DEVICE="tt"

export TT_TRACE=0 # enable trace on decode
export TT_ENABLE_MATERIALIZE=1 # dynamic load
export TT_MESHDEVICE_SHAPE=4,8 # mesh device shape
export QWEN3_MODEL="Qwen3-235B-A22B" # folder that contains the model files
export QWEN3_MODEL_DIR="/mnt/nvme3/" # parent directory that contains the QWEN3_MODEL folder
export TEST_DATASET_PATH="/mnt/nvme3/Qwen3-235B-A22B/test_dataset.json" # path to test_dataset.json, generated by datasets/dataset_generator.py

export MOE_IMPL="snu" # "snu" or "tt"
export MOE_MATMUL_IMPL="moreh_moe_bmm" # "moreh_moe_bmm" or "ttnn.matmul"

MESH_DEVICE=TG_MOREH python examples/server_example_tt.py --model Qwen/Qwen3-235B-A22B --max_model_len 128 --max_num_seqs 128 --override_tt_config '{"sample_on_device_mode": "all"}'