FROM vllm/vllm-openai:v0.13.0

RUN apt-get update && apt-get install -y git
RUN pip uninstall -y vllm
RUN pip install wandb

RUN git clone https://github.com/moreh-dev/vllm.git /root/vllm
WORKDIR /root/vllm
RUN git checkout dump-hidden-states
RUN VLLM_PRECOMPILED_WHEEL_COMMIT=4fd9d6a85c00ac0186aa9abbeff73fc2ac6c721e VLLM_USE_PRECOMPILED=1 pip install --editable .

ENTRYPOINT ["/bin/bash"]
